name: Composer Check

on:
  push:
    paths:
      - composer.json
      - composer.lock
  pull_request:
    paths:
      - composer.json
      - composer.lock

permissions:
  contents: read

jobs:
  build:
    name: Composer Check by Nertoxic
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install
