name: Nertoxic Framework Test

on:
    push:
      paths:
        - '**.php'
        - .env

    pull_request:
      paths:
        - '**.php'
        - .env
    
permissions:
    contents: read

jobs:
    code-review:
        name: Framework Test by Nertoxic
        runs-on: ubuntu-latest

        steps:
        - name: Package Updating
          run: sudo apt-get update

        - name: Checkout
          uses: actions/checkout@v4

        - name: PHP Setup
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'

        - name: Composer installation
          run: composer update

        - name: Run Database test
          working-directory: public/test
          run: php database.php

        - name: Run Framework test
          working-directory: public/test
          run: php framework.php

        - name: Run Mailer test
          working-directory: public/test
          run: php mailer.php
          
        - name: Run Modules test
          working-directory: public/test
          run: php modules.php
