#
# PHP Review
# Checks newly pushed php files
# Made for the Nertoxic Framework
#

name: PHP Review

on:
    push:
      branches: [ "main" ]

    pull_request:
      branches: [ "main" ]
    
permissions:
    contents: read

jobs:
    code-review:
        name: Automatic Code Review by Nertoxic
        runs-on: ubuntu-latest

        steps:
        - name: Package Updating
          run: sudo apt-get update

        - name: Checkout
          uses: actions/checkout@v4

        - name: PHP Setup
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'

        - name: Composer installation
          run: composer update

        - name: Run framework test
          working-directory: public/
          run: php index.php